### PR TITLE
Style

### PR DESCRIPTION
**Pull request by mcconville**
Please review and merge. There are a few things that I'd like to see improved, but I'm running out of time, and they seem tricky to figure out:

- [ ] the tree map, needs moving down a layer when it has only one root element ( California ) - if it has more than one, then fine, show more, but it is not obvious what it is when only one
- [ ] the charts have too many columns - better to reduce them somehow - not one for each year - one for each 5 or 10 years
- [ ] we need a favicon - I was sure I had one for the health records app, but can't see it now
- [ ] the title background and font color for the tree map needs to change, but I don't know how
- [ ] label color on the chart should be navy like the label colors for the other items now
- [ ] the city labels on the map should be navy too #104D81

### CODE REVIEW

**Comment by MaxShapiro32** [comment]
Not sure why the Travis CI build has not completed. It should have finished already. Just a few notes that should be addressed before I merge:

1. `.DS_Store` does not need to be included
2. `apidata.json` does not need to be included
3. Revert `docker-compose.yml` to how it is in the repo
4. Replace `accessToken` on line 415 of `web/public/javascripts/dataHandler.js` with an empty string
5. Replace `mapboxgl.accessToken` on line 14 of `web/public/javascripts/mapHandler.js` with an empty string
6. Where does the `center`, `zoom`, and `minZoom` of the map in `web/public/javascripts/mapHandler.js` start the map? I had it start out where the center is the center longitude/latitude of the United States. The zoom level was also farther out in order to include Alaska and Hawaii
7. `web/public/test.html` probably does not need to be included

For the improvements you mentioned, I will see which I can easily implement.

**Comment by mcconville** [comment]
I agree with all of the above changes, and am sorry for clumsiness in committing things I shouldn't. It was a LOT of effort to both carve the time to work on the style, and add a lot of css classes to create the design I made a while back. It was a relief to commit this at all. I don't have any time to undo the things on this list. So we can choose to wait until next week, or if you can handle these things ( I feel that you could easily do that ) then it would help a lot. I'm sorry.

**Comment by MaxShapiro32** [comment]
I made the changes and the PR is merged. Thanks for updating the style!

**Comment by mcconville** [comment]
Thanks for doing that, and for understanding - it wasn't cool for me to work like this, but I am really trying hard to finish lots of things off this week.

**Pull request merged**
