### PR TITLE
Updated YAML to new Kubernetes API, added resource limits 

### PR DESCRIPTION
**Pull request by fawazsiddiqi**
Updated YAML to new Kubernetes API, added resource limits 

@mridulrb & @fawazsiddiqi (myself) have updated this code pattern with the latest images and Kubernetes API (yaml files)

### CODE REVIEW

**Comment by MaxShapiro32** [comment]
@fawazsiddiqi what is different in your image? Also Travis failed.

**Comment by fawazsiddiqi** [comment]
@MaxShapiro32 Hey Max, **the issue was with the YAML files, they were using the betav1 extensions** thus they weren't working, there are no differences within the image, the travis failed since this is a pull request

**Comment by MaxShapiro32** [comment]
@fawazsiddiqi Can you change the image back to what it was then if it is the same?

From Travis:
```
./deploy-mongodb.yml

  23:7      error    wrong indentation: expected 4 but found 6  (indentation)

  24:11     error    wrong indentation: expected 8 but found 10  (indentation)

  37:17     error    wrong indentation: expected 12 but found 16  (indentation)

./deploy-dataservice.yml

  23:7      error    wrong indentation: expected 4 but found 6  (indentation)

  24:11     error    wrong indentation: expected 8 but found 10  (indentation)

  38:17     error    wrong indentation: expected 12 but found 16  (indentation)

./deploy-webapp.yml

  23:7      error    wrong indentation: expected 4 but found 6  (indentation)

  24:11     error    wrong indentation: expected 8 but found 10  (indentation)

  38:17     error    wrong indentation: expected 12 but found 16  (indentation)

  65:1      error    trailing spaces  (trailing-spaces)

  65:5      error    no new line character at the end of file  (new-line-at-end-of-file)

**Comment by fawazsiddiqi** [comment]
Sure will do that right away

**Comment by fawazsiddiqi** [comment]
closing pull req. and starting a new one due to commit redundancy

**Pull request closed without merging**
